### ISSUE TITLE
Found bug on alice-node

### ISSUE THREAD

**Issue by nd4pa** [NInfolab/alice#21]
Environment : 
-----------------------------

OS : Debian 9
Linux : 4.9.0-4-amd64
node : 8.9.3
npm : 5.5.1

Logs ( alice-node.service ) : 
-------------------------

``` Server listen on http://127.0.0.1:3000
Dec 12 14:32:15 serveur-1 node[810]: /usr/share/alice/node_modules/replacestream/index.js:105
Dec 12 14:32:15 serveur-1 node[810]:       newReplace = newReplace.replace(new RegExp('\\$' + i, 'g'), arguments[i] || '')
Dec 12 14:32:15 serveur-1 node[810]:                               ^
Dec 12 14:32:15 serveur-1 node[810]: TypeError: newReplace.replace is not a function
Dec 12 14:32:15 serveur-1 node[810]:     at regexReplaceFunction (/usr/share/alice/node_modules/replacestream/index.js:105:31)
Dec 12 14:32:15 serveur-1 node[810]:     at getDataToAppend (/usr/share/alice/node_modules/replacestream/index.js:67:41)
Dec 12 14:32:15 serveur-1 node[810]:     at Transform.transform [as _transform] (/usr/share/alice/node_modules/replacestream/index.js:50:28)
Dec 12 14:32:15 serveur-1 node[810]:     at Transform._read (/usr/share/alice/node_modules/readable-stream/lib/_stream_transform.js:182:10)
Dec 12 14:32:15 serveur-1 node[810]:     at Transform._write (/usr/share/alice/node_modules/readable-stream/lib/_stream_transform.js:170:83)
Dec 12 14:32:15 serveur-1 node[810]:     at doWrite (/usr/share/alice/node_modules/readable-stream/lib/_stream_writable.js:406:64)
Dec 12 14:32:15 serveur-1 node[810]:     at writeOrBuffer (/usr/share/alice/node_modules/readable-stream/lib/_stream_writable.js:395:5)
Dec 12 14:32:15 serveur-1 node[810]:     at Transform.Writable.write (/usr/share/alice/node_modules/readable-stream/lib/_stream_writable.js:322:11)
Dec 12 14:32:15 serveur-1 node[810]:     at Stream.ondata (internal/streams/legacy.js:16:26)
Dec 12 14:32:15 serveur-1 node[810]:     at emitOne (events.js:116:13)
Dec 12 14:32:15 serveur-1 systemd[1]: alice-node.service: Main process exited, code=exited, status=1/FAILURE
Dec 12 14:32:15 serveur-1 systemd[1]: alice-node.service: Unit entered failed state.
Dec 12 14:32:15 serveur-1 systemd[1]: alice-node.service: Failed with result 'exit-code'.
Dec 12 14:32:15 serveur-1 systemd[1]: alice-node.service: Service hold-off time over, scheduling restart.
Dec 12 14:32:15 serveur-1 systemd[1]: Stopped Alice node service.
Dec 12 14:32:15 serveur-1 systemd[1]: Started Alice node service.
Dec 12 14:32:15 serveur-1 node[830]: Server listen on http://127.0.0.1:3000
```

Node.js error : 
----------------------------

```
Dec 12 14:32:15 serveur-1 node[810]:       newReplace = newReplace.replace(new RegExp('\\$' + i, 'g'), arguments[i] || '')
Dec 12 14:32:15 serveur-1 node[810]:                               ^
Dec 12 14:32:15 serveur-1 node[810]: TypeError: newReplace.replace is not a function
Dec 12 14:32:15 serveur-1 node[810]:     at regexReplaceFunction (/usr/share/alice/node_modules/replacestream/index.js:105:31)
Dec 12 14:32:15 serveur-1 node[810]:     at getDataToAppend (/usr/share/alice/node_modules/replacestream/index.js:67:41)
Dec 12 14:32:15 serveur-1 node[810]:     at Transform.transform [as _transform] (/usr/share/alice/node_modules/replacestream/index.js:50:28)
Dec 12 14:32:15 serveur-1 node[810]:     at Transform._read (/usr/share/alice/node_modules/readable-stream/lib/_stream_transform.js:182:10)
Dec 12 14:32:15 serveur-1 node[810]:     at Transform._write (/usr/share/alice/node_modules/readable-stream/lib/_stream_transform.js:170:83)
Dec 12 14:32:15 serveur-1 node[810]:     at doWrite (/usr/share/alice/node_modules/readable-stream/lib/_stream_writable.js:406:64)
Dec 12 14:32:15 serveur-1 node[810]:     at writeOrBuffer (/usr/share/alice/node_modules/readable-stream/lib/_stream_writable.js:395:5)
Dec 12 14:32:15 serveur-1 node[810]:     at Transform.Writable.write (/usr/share/alice/node_modules/readable-stream/lib/_stream_writable.js:322:11)
Dec 12 14:32:15 serveur-1 node[810]:     at Stream.ondata (internal/streams/legacy.js:16:26)
Dec 12 14:32:15 serveur-1 node[810]:     at emitOne (events.js:116:13)
```

Detail : 
--------------------------------

Bug seems to occurs at after 2 requests : the first one is slow, but works, the second crashes.

**Comment by nicoladiaz** [comment]
I can confirm on my side with Debian 9 / kernel 4.9.51-1 / nodejs v8.9.3 /  npm : 5.5.1 /
